{{ range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    name: {{ .name}}
spec:
  # {{ if eq .tier "db" }}
  # clusterIP: None
  # {{ else }}
  type: {{ .type }}
  {{ end }}
  ports:
    - port: {{ .port}}
      targetPort: {{ .targetPort}}
  selector:
    name: {{ .selector}}
---
{{ end }}
    